chore: ci 환경을 고려하여 yml 경로 수정

diff --git a/.github/workflows/cicd-workflow.yml b/.github/workflows/cicd-workflow.yml
--- a/.github/workflows/cicd-workflow.yml
+++ b/.github/workflows/cicd-workflow.yml
@@ -30,8 +30,9 @@ jobs:
       - name: Check if config files exist
         run: |
           echo "Current Directory: $(pwd)"
-          ls -al ../config/local
-          cat ../config/local/application-local.yml || echo "❌ yml not found"
+          echo "Current Directory: $(pwd)"
+          ls -al /config/local
+          cat /config/local/application-local.yml || echo "❌ yml not found"
 
       # 3. Gradle 실행 권한 부여
       - name: Grant execute permission for Gradle
