chore: check cloning yml file

diff --git a/.github/workflows/cicd-workflow.yml b/.github/workflows/cicd-workflow.yml
--- a/.github/workflows/cicd-workflow.yml
+++ b/.github/workflows/cicd-workflow.yml
@@ -26,13 +26,20 @@ jobs:
           token: ${{ secrets.ACTION_TOKEN }}
           submodules: true
 
+      # 2-1. 환경변수(yml) 파일이 있는지 확인
+      - name: Check if config files exist
+        run: |
+          echo "Current Directory: $(pwd)"
+          ls -al ../config/local
+          cat ../config/local/application-local.yml || echo "❌ yml not found"
+
       # 3. Gradle 실행 권한 부여
       - name: Grant execute permission for Gradle
         run: chmod +x ./gradlew
 
       # 4. Gradle로 빌드
       - name: Build with Gradle
-        run: ./gradlew clean build -x test
+        run: ./gradlew clean build
 
       # 5. AWS 자격 증명 구성
       - name: Configure AWS credentials
